# Generated by Django 4.2.23 on 2025-08-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0013_alter_bill_code_ext_alter_bill_code_tp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="month",
            field=models.SmallIntegerField(db_column="Month", null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="year",
            field=models.SmallIntegerField(db_column="Year", null=True),
        ),
        migrations.AddField(
            model_name="historicalbill",
            name="month",
            field=models.SmallIntegerField(db_column="Month", null=True),
        ),
        migrations.AddField(
            model_name="historicalbill",
            name="year",
            field=models.SmallIntegerField(db_column="Year", null=True),
        ),
    ]
