# Generated by Django 4.2.23 on 2025-08-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0014_bill_month_bill_year_historicalbill_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="billevent",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="billitem",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="billpayment",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="detailpaymentinvoice",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalbill",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalbillevent",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalbillitem",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalbillpayment",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicaldetailpaymentinvoice",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalinvoice",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalinvoiceevent",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalinvoicelineitem",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalinvoicepayment",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="historicalpaymentinvoice",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="invoiceevent",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="invoicelineitem",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="invoicepayment",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
        migrations.AddField(
            model_name="paymentinvoice",
            name="bill_code",
            field=models.CharField(db_column="BillCode", null=True),
        ),
    ]
