# Generated by Django 4.2.23 on 2025-08-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0016_alter_bill_bill_code_alter_billevent_bill_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billevent",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billitem",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="billpayment",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="detailpaymentinvoice",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbill",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbillevent",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbillitem",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalbillpayment",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaldetailpaymentinvoice",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoice",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoiceevent",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoicelineitem",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalinvoicepayment",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalpaymentinvoice",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoiceevent",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoicelineitem",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="invoicepayment",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="paymentinvoice",
            name="bill_code",
            field=models.CharField(
                blank=True, db_column="BillCode", default=None, max_length=64, null=True
            ),
        ),
    ]
